"""initial

Revision ID: 8fc8dac336df
Revises: 
Create Date: 2026-03-06 14:26:35.496362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fc8dac336df'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('prompt_version_id', sa.String(length=36), nullable=False),
    sa.Column('optimization_run_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('triggered_by', sa.String(length=50), nullable=True),
    sa.Column('pass_count', sa.Integer(), nullable=True),
    sa.Column('fail_count', sa.Integer(), nullable=True),
    sa.Column('total_count', sa.Integer(), nullable=True),
    sa.Column('avg_score', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompt_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('last_parsed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('test_run_id', sa.String(length=36), nullable=False),
    sa.Column('test_case_id', sa.String(length=36), nullable=False),
    sa.Column('actual_output', sa.Text(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('judge_reasoning', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['test_run_id'], ['test_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('prompt_file_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('current_version_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['prompt_file_id'], ['prompt_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('failures',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('prompt_id', sa.String(length=36), nullable=False),
    sa.Column('prompt_version_id', sa.String(length=36), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('source_trace_id', sa.String(length=255), nullable=True),
    sa.Column('input_variables', sa.JSON(), nullable=True),
    sa.Column('actual_output', sa.Text(), nullable=True),
    sa.Column('expected_output', sa.Text(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('failure_category', sa.String(length=50), nullable=True),
    sa.Column('raw_metadata', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('promoted_test_case_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('optimization_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('prompt_id', sa.String(length=36), nullable=False),
    sa.Column('base_version_id', sa.String(length=36), nullable=False),
    sa.Column('result_version_id', sa.String(length=36), nullable=True),
    sa.Column('failure_ids', sa.JSON(), nullable=True),
    sa.Column('test_case_ids', sa.JSON(), nullable=True),
    sa.Column('optimizer_model', sa.String(length=100), nullable=True),
    sa.Column('optimizer_prompt', sa.Text(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('diff', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompt_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('prompt_id', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=10), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('system_message', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('parent_version_id', sa.String(length=36), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('prompt_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('input_variables', sa.JSON(), nullable=True),
    sa.Column('expected_output', sa.Text(), nullable=True),
    sa.Column('eval_method', sa.String(length=50), nullable=True),
    sa.Column('eval_config', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_cases')
    op.drop_table('prompt_versions')
    op.drop_table('optimization_runs')
    op.drop_table('failures')
    op.drop_table('prompts')
    op.drop_table('test_results')
    op.drop_table('prompt_files')
    op.drop_table('test_runs')
    op.drop_table('projects')
    # ### end Alembic commands ###
